apiVersion: apps/v1
kind: Deployment
metadata:
  name: video-streaming
spec:
  selector:
    matchLabels:
      app: video-stream
  replicas: 2
  template:
    metadata:
      labels:
        app: video-stream
    spec:
      containers:
      - name: video-stream
        image: grupo1SD.azurecr.io/video-streaming:latest
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: video-streaming
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: video-stream