name: Docker Image CI

on:
  push:
    branches: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
           version: latest
           
    - name: Build the Docker image
      run: docker buildx build ./video-streaming-example-master/ --file Dockerfile \
          --tag 2044318/my-image-name:$(date +%s) \
          --platform=linux/arm/v7
