name: Docker Image CI

on:
  push:
    branches: [main]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: checkout code
      uses: actions/checkout@v2
    - name: install buildx
      id: buildx
      uses: crazy-max/ghaction-docker-buildx@v1
      with:
           version: latest
           
    - name: Build the Docker image
      run: docker buildx build --file Dockerfile \
          --platform=linux/arm/v7 \
          --tag 2044318/video-streaming:$(date +%s) \
          ./video-streaming-example-master
